baseURL = 'https://vnturing.github.io/'
languageCode = 'en-us'
title = 'Turing Complete'
theme = 'typo'

[params]
# Meta description
description = "Exploring the intersection of society and technology, through a philosophical lense."
rss = true

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm a software engineer and writer. I have spent the last few years in a love-hate relationship with technology. Will the tech industry ever be better than this?
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listDateFormat = '2 Jan 2006'

footerContent = """
&copy; 2026 Turing Complete \\
Any opinions listed here are my own and not representative of any of my employers, past and/or present. \\
Powered by [Hugo](https://gohugo.io) and [Typo](https://github.com/tomfran/typo)
"""

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"


[[params.social]]
name = "github"
url = "https://github.com/vnturing"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
noClasses = false

[caches]
[caches.images]
dir = ':cacheDir/images'

[params.umami]
enable = true
websiteId = '1f65872c-f35e-44fb-97a8-243bb04eb53d'
jsLocation = 'https://cloud.umami.is/script.js'


[[params.social]]
name = "rss"
url = "/index.xml"
