baseURL = 'https://vnturing.github.io/'
languageCode = 'en-us'
title = 'Turing Complete'
theme = 'typo'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm a software engineer and writer. I have spent the last few years in a love-hate relationship with technology. Will the tech industry ever be better than this?
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"


[[params.social]]
name = "github"
url = "https://github.com/vnturing"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
noClasses = false

[caches]
[caches.images]
dir = ':cacheDir/images'